#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : swupd-search
Version  : 22
Release  : 18
URL      : http://localhost/cgit/projects/swupd-local-search/snapshot/swupd-local-search-22.tar.xz
Source0  : http://localhost/cgit/projects/swupd-local-search/snapshot/swupd-local-search-22.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: swupd-search-bin = %{version}-%{release}

%description
No detailed description available

%package bin
Summary: bin components for the swupd-search package.
Group: Binaries

%description bin
bin components for the swupd-search package.


%prep
%setup -q -n swupd-local-search-22
cd %{_builddir}/swupd-local-search-22

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578345975
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1578345975
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/swupd-search
