#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : swupd-search
Version  : 2
Release  : 1
URL      : http://localhost/cgit/projects/swupd-local-search/snapshot/swupd-local-search-2.tar.xz
Source0  : http://localhost/cgit/projects/swupd-local-search/snapshot/swupd-local-search-2.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0

%description
No detailed description available

%prep
%setup -q -n swupd-local-search-2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550436436
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1550436436
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/swupd-search
